# version1-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  selector:
    matchLabels:
      app: nginx
      version: 'v1.0'
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx
        version: 'v1.0'
    spec:
      containers:
      - name: nginx
        image: my_project/web-app:version1
        ports:
        - containerPort: 80
