# version2-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
spec:
  selector:
    matchLabels:
      app: nginx
      version: 'v1.1'
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx
        version: 'v1.1'
    spec:
      containers:
      - name: nginx
        image: my_project/web-app:version2
        ports:
        - containerPort: 80
